* The point.
Everything starts with a point.
* Focus on iterations.
* Ideas
Cross-eye viewing without crossing eyes / prism : [example] http://www.berezin.com/3d/3dprism.htm
* Sources
Learn some scheme, yet? http://scheme.com/tspl4/
* Interesting?
What is interesting?
What does it mean?
What is "what"?
What is?
No point here.
Instead - I have thoughts. Let's omit the question if I have I for now.
Then. These thoughts. Some of them are - interesting thoughts. 
Then, this idea of self-destruction. On the high level I agree that it should not be done. Deep inside, however, it works.
I am afraid. Sourin or not, I am afraid.
I am alone, too. This sounds even worse if there is no I. noI am alone and not exist anyway.
Meaning disappears.
Nothing there... memory is failing. 
Let's continue to pretend.
(At least writing is there, to certain extent :)

* Tools
Description and configuration of thools for dots.
** Github
git push origin master
** Emacs
Minimal configuration runnable on most emacsen. 
[[file:.emacs][.emacs]]



