* The point.
Everything starts with a point.
* Focus on iterations.
* Ideas
** /etc/hosts
74.125.235.48 livejournal.com reddit.com ycombinator.com lenta.ru xkcd.com bash.org.ru zadolba.li killmepls.ru ithappens.ru svezlo.net det.org.ru slashdot.org fmylife.com
Does not work on all subdomains.
** Storage organization
The point of dot is to keep all _my_ ideas covered.
Main things go to core.org
Referenced from log.org
Then, certain files with different extensions might go into 
points/ and be under version control.
Then, there are things not written by me, but nice to be able to reference them.
1. External folder
2. Internal folder
1 - good as no interference with dot. Bad for reference.
2 - Good for reference, but will interfere vith version control. (As those things don't need VC)
** 3D
Cross-eye viewing without crossing eyes / prism : [example] http://www.berezin.com/3d/3dprism.htm
** Possible tools:
Statistics http://www.rstudio.org
* Sources
Learn some scheme, yet? http://scheme.com/tspl4/
* Interesting?
What is interesting?
What does it mean?
What is "what"?
What is?
No point here.
Instead - I have thoughts. Let's omit the question if I have I for now.
Then. These thoughts. Some of them are - interesting thoughts. 
Then, this idea of self-destruction. On the high level I agree that it should not be done. Deep inside, however, it works.
I am afraid. Sourin or not, I am afraid.
I am alone, too. This sounds even worse if there is no I. noI am alone and not exist anyway.
Meaning disappears.
Nothing there... memory is failing. 
Let's continue to pretend.
(At least writing is there, to certain extent :)

* Tools
 Description and configuration of tools for dots.
** Org
http://orgmode.org/guide
** Github
[[shell:git push origin master]]
** Emacs
https://github.com/matburt/mobileorg-android/wiki/ ?
Minimal configuration runnable on most emacsen. 
[[file:.emacs][.emacs]]
*** Keybindings
   Set key: (global-set-key (kbd "C-z") 'undo)
[[http://xahlee.org/emacs/keyboard_shortcuts.html][Site with keybinding examples]]
*** Choose browser
(setq 
 browse-url-browser-function 'browse-url-generic 
 browse-url-generic-program "chromium-browser") 

