* The point.
Everything starts with a point.
* Focus on iterations.
* Ideas
** /etc/hosts
74.125.235.48 livejournal.com reddit.com ycombinator.com lenta.ru xkcd.com bash.org.ru zadolba.li killmepls.ru ithappens.ru svezlo.net det.org.ru slashdot.org fmylife.com
Does not work on all subdomains.
** Storage organization
The point of dot is to keep all _my_ ideas covered.
Main things go to core.org
Referenced from log.org
Then, certain files with different extensions might go into 
points/ and be under version control.
Then, there are things not written by me, but nice to be able to reference them.
1. External folder
2. Internal folder
1 - good as no interference with dot. Bad for reference.
2 - Good for reference, but will interfere vith version control. (As those things don't need VC)
** 3D
Cross-eye viewing without crossing eyes / prism : [example] http://www.berezin.com/3d/3dprism.htm
** Possible tools:
Statistics http://www.rstudio.org
* Sources
Learn some scheme, yet? http://scheme.com/tspl4/
* Interesting?
** Rant One:
What is interesting?
What does it mean?
What is "what"?
What is?
No point here.
Instead - I have thoughts. Let's omit the question if I have I for now.
Then. These thoughts. Some of them are - interesting thoughts. 
Then, this idea of self-destruction. On the high level I agree that it should not be done. Deep inside, however, it works.
I am afraid. Sourin or not, I am afraid.
I am alone, too. This sounds even worse if there is no I. noI am alone and not exist anyway.
Meaning disappears.
Nothing there... memory is failing. 
Let's continue to pretend.
(At least writing is there, to certain extent :)

** Rant two:
Read it.
Why I dont do what I want?
I hate reading junk.
I, in a sense, want to write to Sourin.
I could do many things.
I don't.
Please.
Help.
Please...
I can. I really CAN. Do something. 
I am going to go and sleep now. And think that tomorrow - really, tomorrow, I will be great.
I will write this small tool for 3D interaction and edetinig.
With multiresolution. And friends.
But. And this is a huge "but". I will not be able to do it. I will be reading junk and stuff again. Whinch can not be interesting. Because, it DOES NOT EXIST. Why? maybe prohibition has to be lifted? From this question, altogether. 
Right, it would not.
I need to lift it. And go with it.
Please. Continue. Drifting away. This is better. Whatever you say.
Nothing. Notice how time slows down when writing things. It does not always do so when writing software, probably because lots of trial and error is involved. Theory says - emacs can help with this train of thought thing.
Good. Bye.
See you in another life.
Feeling of crashing down. In between. Let's focus on feelings.
* Tools
 Description and configuration of tools for dots.
** Org
http://orgmode.org/guide
** Github
[[shell:git push origin master]]
** Emacs
https://github.com/matburt/mobileorg-android/wiki/ ?
Minimal configuration runnable on most emacsen. 
[[file:.emacs][.emacs]]
*** Keybindings
   Set key: (global-set-key (kbd "C-z") 'undo)
[[http://xahlee.org/emacs/keyboard_shortcuts.html][Site with keybinding examples]]
*** Choose browser
(setq 
 browse-url-browser-function 'browse-url-generic 
 browse-url-generic-program "chromium-browser") 

** GLFW
Universal Minimal Opengl framework.
http://www.glfw.org/
[[ shell:wget http://www.glfw.org/GLFWUsersGuide27.pdf]] [[file:GLFWUsersGuide27.pdf]]
[[ shell:wget http://www.glfw.org/GLFWReference27.pdf]] file:GLFWReference27.pdf
http://wiki.glfw.org/wiki/Main_Page
** Installing on ubuntu:
sudo apt-get install libglfw-dev libglu1-mesa-dev 

Trying:
[[file:points/gl/main.cpp::Testing%20ground%20for%20GLFW][Sample glfw]]
