* Purpose
Leave notes as I do things and come up with ideas. 
Text searching might be interesting.
* Things to log:
** Buy small screwdrivers to repair notebook.
** Answer Sourin
** Insurance for Lev
 NTUC
** Yulia's motorcycle
 LTA  
** Phantom advertisement
** GLFW core
 Find a way to put small code in dot.
* Fri Feb 25 11:29:34 SGT 2011
** Java runtimes organization
How to organize java runtimes:
Information needed: jvm/jre, version, SR.
One option - jvm/jre-[version]-sr[number]
Sun - jvm/jre-[version]-sun
find ~/work -name javac
** JSSE 1.5 compilation and testing
Verified jsse150.
Copying does not work, let's check the original version.
Original version does work. Replacing separate jars might solve the problem.
Replacing separate class files did not really work, as the jar is objuscated...
Sent failure report to Audrey.
More ideas:
Use classpath.
Make eclipse project and play there.
Put it all into eclipse.

** Setting up general emacs configuration:
 Basic configuration useful on generic emacs install.
 [[file:core.org::*Emacs%20configuration][Core idea]]
 [[file:.emacs]]


 Answerred Nadia/Hari/David
* Sat Feb 26 00:41:48 SGT 2011
Go!
** Bills
 Starhub
 Utilities
 
** Заметки
Лев качался на детской площадке - радовался.
Взял в заложники шоколадку на автозаправке. Шоколадка была обменяна на пачку кофе.
Пока кормились в фудкорте, встретили продавца машины. Еле узнал.
** Things I want to know.
 - Organize knowledge
 - GLFW basics
 - Emacs stuff

* Sun Feb 27 00:20:10 SGT 2011
Sourin!!!
Nope.
Instead, going woth Lev,
Accompanying Yulia to spa,
Shopping, then Trying to help Lev fall asleep.
And lot's of time lost.
important finding - 
 Now that I've got this system for storing results reliably - 
  It is visible that loosing them is not the reason for acheiving.
 ToRead:
Interesting use of makefiles: 
http://www.ibm.com/developerworks/linux/library/l-boot.html
Godel theorem (I am not sure I know non-generalized, either)
http://blog.sigfpe.com/2011/02/generalising-godels-theorem-with.html

* Mon Feb 28 xx:xx:xx SGT 2011
Do something today!
The main question is : Why? 
Shape modeling 
* Thu Mar  3 01:32:37 SGT 2011
GLFW started again.
* Thoughts:
Log should not always have dates. 
Dates matter sometimes. When one does not anticipate the use of date,
it can be determined with git history, anyway. So, simpler would be to omit dates altogether.
* EKM, beginning:todo:
Download link: 
 http://www-933.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~ST~Tapedevicedriversandsoftware&product=ibm/Storage_Tape/Encryption+Key+Manager+EKM&release=1.0&platform=Linux&function=fixId&fixids=EKM&includeRequisites=1&downloadMethod=http&source=fc
Working folder:
file:/home/kdl/work/EKM_Training
[[file:~/work/EKM_Training/EKM_a_userguide.pdf][Install guide]]
** next:
Install, try CLI commands.
* Interview, 8 march.
Phone interview - 2nd rd (SE Dev) - 
- Note for next interviewers;
can be asked in detail:
- high level design questions & architecture questions.
- OOP related question analysis and design
- Operating System questions
** next: 
Come up with problems.
Fair scheduling.
* JS58
file:~/work/JS58/readme.org
Takes too much time, use java profiler:
(Builtin one)
java -agentlib:hprof=cpu=samples,interval=20,depth=3 Test
http://java.sun.com/developer/technicalArticles/Programming/HPROF.html
