* Purpose
Leave notes as I do things and come up with ideas. 
Text searching might be interesting.
* Things to log:
** Buy small screwdrivers to repair notebook.
** Answer Sourin
** Insurance for Lev
 NTUC
** Yulia's motorcycle
 LTA  
** Phantom advertisement
** GLFW core
 Find a way to put small code in dot.
* Fri Feb 25 11:29:34 SGT 2011
** Java runtimes organization
How to organize java runtimes:
Information needed: jvm/jre, version, SR.
One option - jvm/jre-[version]-sr[number]
Sun - jvm/jre-[version]-sun
find ~/work -name javac
** JSSE 1.5 compilation and testing
Verified jsse150.
Copying does not work, let's check the original version.
Original version does work. Replacing separate jars might solve the problem.
Replacing separate class files did not really work, as the jar is objuscated...
Sent failure report to Audrey.
More ideas:
Use classpath.
Make eclipse project and play there.
Put it all into eclipse.

** Setting up general emacs configuration:
 Basic configuration useful on generic emacs install.
 [[file:core.org::*Emacs%20configuration][Core idea]]
 [[file:.emacs]]


 Answerred Nadia/Hari/David
* Sat Feb 26 00:41:48 SGT 2011
Go!
** Bills
 Starhub
 Utilities
 
** Заметки
Лев качался на детской площадке - радовался.
Взял в заложники шоколадку на автозаправке. Шоколадка была обменяна на пачку кофе.
Пока кормились в фудкорте, встретили продавца машины. Еле узнал.
** Things I want to know.
 - Organize knowledge
 - GLFW basics
 - Emacs stuff

* Sun Feb 27 00:20:10 SGT 2011
Sourin!!!
Nope.
Instead, going woth Lev,
Accompanying Yulia to spa,
Shopping, then Trying to help Lev fall asleep.
And lot's of time lost.
important finding - 
 Now that I've got this system for storing results reliably - 
  It is visible that loosing them is not the reason for acheiving.
 ToRead:
Interesting use of makefiles: 
http://www.ibm.com/developerworks/linux/library/l-boot.html
Godel theorem (I am not sure I know non-generalized, either)
http://blog.sigfpe.com/2011/02/generalising-godels-theorem-with.html

* Mon Feb 28 xx:xx:xx SGT 2011
Do something today!
The main question is : Why? 
Shape modeling 
* Thu Mar  3 01:32:37 SGT 2011
GLFW started again.
* Thoughts:
Log should not always have dates. 
Dates matter sometimes. When one does not anticipate the use of date,
it can be determined with git history, anyway. So, simpler would be to omit dates altogether.
* EKM, beginning:todo:
Download link: 
 http://www-933.ibm.com/support/fixcentral/swg/quickorder?parent=ibm~ST~Tapedevicedriversandsoftware&product=ibm/Storage_Tape/Encryption+Key+Manager+EKM&release=1.0&platform=Linux&function=fixId&fixids=EKM&includeRequisites=1&downloadMethod=http&source=fc
Working folder:
file:/home/kdl/work/EKM_Training
[[file:~/work/EKM_Training/EKM_a_userguide.pdf][Install guide]]
** next:
Install, try CLI commands.
What installation must look like?
* Interview, 8 march.
Phone interview - 2nd rd (SE Dev) - 
- Note for next interviewers;
can be asked in detail:
- high level design questions & architecture questions.
- OOP related question analysis and design
- Operating System questions
** next: 
Come up with problems.
Fair scheduling.
* JS58
file:~/work/JS58/readme.org
Takes too much time, use java profiler:
(Builtin one)
java -agentlib:hprof=cpu=samples,interval=20,depth=3 Test
http://java.sun.com/developer/technicalArticles/Programming/HPROF.html
Ok, as it is as slow in 1.6 as in 1.5, no regression happened, 
so we are in the clear.
* JS55
** Problem
EKM, Install in windows.
Probable cause - training slash.
[[file:~/work/JS55/readme.org::*Description][details]]
** Solution
JAVA_HOME, remove traing slash.
* Mounting VM disk, finally, good solution:
in qemu:
(qemu) hostfwd_add tcp::1445-:445
then 
sudo mount.cifs //localhost/C$ /vm/mounted -o port=1445,user=Administrator,password=1q2w3e4r
Just Works.
(samba needs to be installed, but no stupid stuff on the vm)

* Phantom for sale.
http://singaporebikes.com
** Postings:
https://post.craigslist.org/manage/2248160431/zvani
http://www.singaporebikes.com/classifieds/showproduct.php?product=10331
(Photos in gmail)
** Text:
Nice and unusual phantom for sale!
Running condition and good transport bike.
Mileage is low, too, as it was underused.

Catch? Yes, COE expiring in August.

Can get non-renewable 5 yr. COE after that in any bike shop.

And the low-low price is discussable, too.

Please let me know if you are interested to buy, see, or talk :) SMS/Call Konst@91007930.

Thanks!
** Waiting for reply.
* WebGL explore
Need t go from the official chronos site.
